### ISSUE TITLE
Selecting multiple ingredients behavior

### ISSUE THREAD

**Issue by zsmoore** [Whos-Hungry/dashboard-app#108]
There are some weird things happening with filtering.

Selecting multiple ingredients doesn't seem to give recipes containing both ingredients, rather fills the screen with recipes that include one or the other

**Comment by jacobfij** [comment]
We are aware of this, and are currently deciding on how to handle this issue.  I believe the current path is going to be adding an 'ingedient score' which would say how many of the items a recipe contains, so you would still get recipes that don't have every single ingredient, but the ones with more ingredients would come up first.

**Comment by jacobfij** [comment]
We've added ingredient 'similarity scores' for each recipe, which we are considering the solution to this issue. See issue #133.
