### ISSUE TITLE
De-selecting ingredients Bug

### ISSUE THREAD

**Issue by zsmoore** [Whos-Hungry/dashboard-app#109]
If you search with a filter then delete an ingredient and re-search with a new ingredient it does not de-select the deleted ingredient in the background.

Ex.  
Select Flour
Find Recipes
Delete Flour
Select Avocado
Find Recipes

Flour recipes still present

**Comment by zsmoore** [comment]
Tied into this, you can't get random recipes again if you deselect everything.

**Comment by jacobfij** [comment]
Yep. caught this when modifying the sidebar earlier this week.  Those changes just haven't been pushed to the production server yet.  I'll leave this issue open for the moment, for verification when we update.
