### ISSUE TITLE
Recipe name text not displayed correctly

### ISSUE THREAD

**Issue by zsmoore** [Whos-Hungry/dashboard-app#110]
It look's like the text grabbed from the recipe name is not being interpreted for special characters.

See picture.
![text](https://user-images.githubusercontent.com/8812688/32360712-068f385e-c02f-11e7-802e-5f2fd8ba2800.png)

**Comment by jacobfij** [comment]
This is one of our 'help wanted' tasks, actually..  See #106. Closing this issue as a duplicate.
