### ISSUE TITLE
Log out user when refresh page behavior

### ISSUE THREAD

**Issue by zhenkangub** [Whos-Hungry/dashboard-app#113]
If a user is logged in, refresh the page will log out the user. I think in most website, refresh won't log out the user, so I hope this could be fixed, and hopefully it will improve the user experience!

**Comment by devnocs** [comment]
As mentioned on ryver, react starts a new application when you refresh the page, so that's the reasoning for that. We'll look at persisting across refreshes.

**Comment by devnocs** [comment]
Merged, so closing
