### ISSUE TITLE
Security bug of the website

### ISSUE THREAD

**Issue by QinxinTian** [Whos-Hungry/dashboard-app#114]
<img width="1175" alt="2017-11-04 3 54 57" src="https://user-images.githubusercontent.com/25886116/32403577-0541b9dc-c114-11e7-8620-d5241a1dac5d.png">
<img width="1271" alt="2017-11-04 3 54 41" src="https://user-images.githubusercontent.com/25886116/32403578-0799564a-c114-11e7-9914-28f30bba9331.png">

**Comment by rachelaroberts** [comment]
<img width="854" alt="screen shot 2017-11-04 at 12 42 36 pm" src="https://user-images.githubusercontent.com/10821798/32407323-a9e79094-c15d-11e7-82c7-76d7e8a8880f.png">
You can change the local HTML of literally any website. Closing this issue.
