### ISSUE TITLE
Bug: sign up

### ISSUE THREAD

**Issue by chandx** [Whos-Hungry/dashboard-app#116]
There are at least 3 bugs in sign up
1. it has limited check for email form, example
input: "sa@" passed.
input: "@" output:
> Unhandled Rejection (TypeError): Cannot read property 'response' of undefined
(anonymous function)
src/actions/homepage.js:73
  70 | const url = 'https://api.whoshungry.io/session/create-user'
  71 | const options = { method: 'POST', body: JSON.stringify(user) };
  72 | return dispatch => hitApi(url, options).then((payload) => {
> 73 |   if (payload.response === 'error') {
  74 |     dispatch({ type: ERROR, payload});
  75 |     return;
  76 |   }

2. there is no check for password security. Even it could be 1 character.
3. it cannot sign up two users with identical prefix email. eg. "wasd@126.com" and "wasd@163.com" , it will show error for the second attempted user:

> Unhandled Rejection (TypeError): Cannot read property 'response' of undefined
(anonymous function)
src/actions/homepage.js:73
  70 | const url = 'https://api.whoshungry.io/session/create-user'
  71 | const options = { method: 'POST', body: JSON.stringify(user) };
  72 | return dispatch => hitApi(url, options).then((payload) => {
> 73 |   if (payload.response === 'error') {
  74 |     dispatch({ type: ERROR, payload});
  75 |     return;
  76 |   }

**Comment by jacobfij** [comment]
One of our collaboration tasks was adding constraints to these types of things.  We've also separated the username from email, so the duplicate email prefixes will also be handled.

**Comment by chandx** [comment]
However, I think it should consider the situation that one person uses email "wasd@gmail.com"
and another person uses "wasd@yahoo.com", they can be different people

**Comment by jacobfij** [comment]
Correct. So the current method is to extract the email prefix as the username. That's what causes the issue with that. We've since separated them completely, so there is one field for username, and one for email. So it will allow the two different emails and just require different usernames.

**Comment by jacobfij** [comment]
I'll leave this ticket open for verification once we update the production server.
