### ISSUE TITLE
Bug: It does not really searching anything. It returns me wrong searching results.

### ISSUE THREAD

**Issue by QinxinTian** [Whos-Hungry/dashboard-app#118]
[Screen Capture 4.mov.zip](https://github.com/Whos-Hungry/dashboard-app/files/1443728/Screen.Capture.4.mov.zip)
It gave me the wrong searching result, when I tried to search "beef", it gave me the result of the chicken or the apple pie, when I tried the "chicken", it gives me the seafood or the bread. It does look like that the "searching" function isn't actually working, it just generates a lot of the results without any logic.

**Comment by jacobfij** [comment]
I believe this may have been a misuse of the search function, when using the searchbar, it looks up ingredients to add to the 'pantry'.  If you put text in the searchbar and click the 'find recipes' button, it would end up returning random recipes.

**Comment by devnocs** [comment]
As not a bug but rather a design choice
