### ISSUE TITLE
Search Issue

### ISSUE THREAD

**Issue by VikramGaru** [Whos-Hungry/dashboard-app#93]
Even on entering random invalid characters, the application shows recipes instead of giving error.

**Comment by jacobfij** [comment]
Can you specify what you mean? Typing characters into the search bar shouldn't change the recipes.  The search bar is used to add ingredients to your 'pantry'.

**Comment by VikramGaru** [comment]
If I type in any random word or even random characters the application returns recipes. However, it should not return any recipes as such a recipe does not exist. I hope this clarifies the issue.

**Comment by rachelaroberts** [comment]
@VikramGaru Our app does not allow you to type in jibberish, add it to your pantry, and find recipes. It only allows you to pick from pre-existing ingredients and add those to your pantry, and THEN find recipes. It does, however, return random recipes if you click on the "find recipes" button without anything checked in your pantry. This is what it is doing to you. You aren't adding jibberish to your pantry.

**Comment by rachelaroberts** [comment]
I am now closing this issue, since we made it more intuitive to avoid this confusion.
