### ISSUE TITLE
Typing Issue in Search Bar

### ISSUE THREAD

**Issue by VikramGaru** [Whos-Hungry/dashboard-app#94]
Sometimes when typing into the search bar, the words get distorted and the desired word does not appear

**Comment by jacobfij** [comment]
Looking into this.

**Comment by j3kstrum** [comment]
Found this to be the case as well

**Comment by jacobfij** [comment]
Yeah, it's an issue with the way it's rerendering. Essentially it's waiting until it's gets all the suggestions from the backend before updating the value to display, so if you type too fast, you can beat it to updating the input and it screws up.
